PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
    {
        ?x a dbo:City .
        ?x ?y dbr:United_States .
    }
    UNION
    {
        ?x a dbo:City .
        dbr:United_States ?z  ?x .
    }
} LIMIT <number>