PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>
SELECT DISTINCT ?x WHERE
{
    {
    	?x a dbo:Book .
    	?y1 dbo:series ?x .
    	?y1 a dbo:WrittenWork .
    	?y2 dbo:series ?x .
    	?y2 a dbo:WrittenWork .
    }
    FILTER
    (
        ?y1 != ?y2
    )
}