PREFIX dbr: <http://dbpedia.org/resource/>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT DISTINCT ?x WHERE
{
    {
        ?x a dbo:Album .
        ?x ?r1 ?z .
        ?z ?r2 dbr:New_York_City .
    }
    UNION
    {
        ?x a dbo:Album .
        ?z ?y1 ?x .
        dbr:New_York_City ?y2 ?z .
    }
} LIMIT <number>