PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
    ?x a dbo:Book .
    FILTER
    (
        NOT EXISTS
        {
            ?x ?y dbr:Science_fiction .
        }
        &&
        NOT EXISTS
        {
            dbr:Science_fiction ?z ?x .
        }
    ) .
} LIMIT <number>