PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
    {
    	?x a dbo:Person .
        ?x dbo:recordLabel ?y1 .
        ?y1 a dbo:RecordLabel .
        ?x dbo:recordLabel ?y2 .
        ?y2 a dbo:RecordLabel .
    }
    FILTER
    (
        ?y1 != ?y2
    )
} LIMIT <number>