PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT DISTINCT ?x WHERE {
    ?x a dbo:Species .
    ?x dbo:kingdom ?y .
    FILTER
    (
        NOT EXISTS
        {
            ?y dbo:kingdom ?x .
        }
    ) .

} LIMIT <number>