PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
	?x a dbo:City .
  	?x 	dbo:namedAfter ?y1 .
  	?y1 a dbo:Place .
  	?x dbo:namedAfter ?y2 .
  	?y2 a dbo:Place .
  FILTER (?y1 != ?y2 ) .
} LIMIT <number>