PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
    {
        {
            ?x a dbo:Film .
            ?x ?r1 ?z .
        }
        FILTER
        (
            NOT EXISTS
            {
                ?z ?r2 dbr:New_York_City .
            }
            &&
            NOT EXISTS
            {
                dbr:New_York_City ?r3 ?z .
            }
        ) .
    }
    MINUS
    {
            {
                ?x a dbo:Film .
                ?z ?r1 ?x .
            }
            FILTER
            (
                 NOT EXISTS
                {
                    ?z ?r2 dbr:New_York_City .
                }
                &&
                NOT EXISTS
                {
                    dbr:New_York_City ?r3 ?z .
                }
            ) .
        }
} LIMIT <number>