PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT DISTINCT ?x WHERE {
    {
        ?x a dbo:City .
        ?y dbo:namedAfter ?x .
    }
    UNION
    {
        ?x a dbo:City .
        ?x dbo:namedAfter ?y .
    }
} LIMIT <number>
