PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
    {
        ?x a dbo:Film .
        ?y dbo:knownFor ?x .
    }
    FILTER
    (
        NOT EXISTS
        {
            ?z dbo:knownFor ?x .
            FILTER
            (
                ?y != ?z
            ) .
        }
    )
} LIMIT <number>