PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
    {
        ?x a dbo:Species .
        ?x ?y dbr:Animal .
    }
    UNION
    {
        ?x a dbo:Species .
        dbr:Animal ?z  ?x .
    }
} LIMIT <number>