PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
    {
    	?x a dbo:City .
    	?y1 dbo:city ?x .
        ?y1 a dbo:EducationalInstitution .
    }
    FILTER
    (
        NOT EXISTS
        {
                ?y2 dbo:city ?x .
                ?y2 a dbo:EducationalInstitution .
            FILTER
            (
                ?y1 != ?y2
            ) .
        }
    ) .
} LIMIT <number>