PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x ?r1 ?z ?r2 WHERE
{
    {
        ?x a dbo:Species .
        ?x ?r1 ?z .
        ?z ?r2 dbr:New_York_City .
    }
    UNION
    {
        ?x a dbo:Species .
        ?z ?y1 ?x .
        dbr:New_York_City ?y2 ?z .
    }
} LIMIT <number>