PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbr: <http://dbpedia.org/resource/>

SELECT DISTINCT ?x WHERE
{
    {
        ?x a dbo:Film .
        ?x dbo:director ?y .
    }
    FILTER
    (
        NOT EXISTS
        {
            ?x dbo:director ?z .
            FILTER
            (
                ?y != ?z
            )
        }
    ) .
} LIMIT <number>